#!/bin/bash --login

#SBATCH --job-name qscript
#SBATCH --nodes=1              # Request one node
#SBATCH --tasks-per-node=128   # Request 128 tasks per node
#SBATCH --cpus-per-task=1      # Request one cpu per task
#SBATCH --time=00:20:00

#SBATCH --account=ta006
#SBATCH --partition=standard
#SBATCH --qos=standard



# f90wrap runtime: assumes f90wrap is installed in the current
# directory as described in the Makefile

export PYTHONPATH=`pwd`/f90wrap/lib/python3.8/site-packages:$PYTHONPATH

srun python ./mpi-driver.py
